### ISSUE TITLE
Internal Symbols are shown as unknown

### ISSUE THREAD

**Issue by heiglandreas** [maglnet/ComposerRequireChecker#3]
I've just checked a component that shows ```DateTime```, ```DateTimeZone```, ```Countable```, ```RecursiveIterator``` or ```InvalidArgumentException``` as unknown.

The Symbols are declared in the files via a ```use```-Statement.

**Comment by maglnet** [comment]
Hi,
for now only the extensions "Core" and "standard" are checked when "php" is a requirement.
Could you please try adding the following extensions to your `require` section and check again:
`"ext-date" : "*"` for `DateTime`, `DateTimeZone`
`"ext-spl" : "*"` for `Countable`, `RecursiveIterator` and `InvalidArgumentException` 

We should think about, how restrictive ComposerRequireChecker should be, since I don't know how minimal a PHP installation could be.
I think everything that can be ommitted when compiling PHP should not be checked automatically, but i don't have a source where I can see, what is a minimum to compile and run PHP.

**Comment by maglnet** [comment]
I think i found it, the extensions listed as "Core Extensions" in the following link should be configured as default, when `php` is required:
http://php.net/manual/en/extensions.membership.php

**Comment by maglnet** [comment]
As decided in #6, all extensions that are available when PHP is compiled with `--disable-all` are now whitelisted per default.
So, all extensions mentioned above should not be marked as unknown in the next release.

**Comment by Ocramius** [comment]
Note: it may be worth starting to differentiate these issues by "severity". A non-included core dependency could be "notice" level

**Comment by maglnet** [comment]
But is it this tools decision, what severity an unknown symbol ist?
As you could find a php installation without `ext-json`, why not force users to define it as a dependency, when using `json_encode` / `json_decode`?

**Comment by Ocramius** [comment]
@maglnet severity as in "instanceof" vs "API usage", for example. Type-hinting vs instantiating, etc. Some cause hard breakages, some are more "soft"

**Comment by maglnet** [comment]
ok, I think I understand, could be hard to check because we need to figure out, if a symbol is used within an `instanceof` block, or not, right?

**Comment by Ocramius** [comment]
Yup. Of course it's a suggestion - should I open an issue?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by maglnet** [comment]
Yes, please.
