### ISSUE TITLE
Unresolved `getallheaders` function

### ISSUE THREAD

**Issue by xepozz** [maglnet/ComposerRequireChecker#359]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/6815714/198726261-7f1b90ba-cf6b-405f-9924-54ca211f6316.png">
The [documentation](https://www.php.net/manual/en/function.getallheaders.php) says that it's available from FPM SAPI
I have no idea how to fix it :)

**Comment by Ocramius** [comment]
I would suggest adding an exclusion for it in your own config: `getallheaders()` is indeed conditionally present, so it cannot be considered always existing by default.

I don't think `composer.json` has a way to target a specific SAPI, since you'd need to run `composer install` with that SAPI too...
