### ISSUE TITLE
Accept extensions defined in `config.platform`

### ISSUE THREAD

**Issue by hkdobrev** [maglnet/ComposerRequireChecker#66]
Composer would accept `config.platform` versions when resolving dependencies even if they are not present on a local installation. Could the require checker use that and do not report missing extensions when they are defined in `config.platform`?
This of course assumes the versions you define in `config.platform` are really present on your production environment.

Links:
- [Platform packages](https://getcomposer.org/doc/01-basic-usage.md#platform-packages)
- [`config.platform`](https://getcomposer.org/doc/06-config.md#platform)

**Comment by maglnet** [comment]
The problem with this one is, that an unknown function can not reliable be matched to an extension.

Let's say you define `ext-foo` within your `config.platform` and you're using function `bar()` (defined by `ext-foo`).
Since `ext-foo` with all its functions isn't available we have no chance to find out if the extension would have defined this function and so the `config.platform` setting is useless for us.

In this case you should create a custom config for ComposerRequireChecker that whitelists the functions defined by `ext-foo`. (see https://github.com/maglnet/ComposerRequireChecker#configuration)
