### ISSUE TITLE
Configuration options to include packages from require-dev and suggests

### ISSUE THREAD

**Issue by Majkl578** [maglnet/ComposerRequireChecker#70]
It seems that currently only packages used directly in `require` section are considered.
There are multiple cases when packages are optional dependency and as such are only present in `suggest` (and possibly also `require-dev`) section. These are currently reported as missing dependency, although they are not  hard dependency.

**Comment by Ocramius** [comment]
This is exactly what this package is about: finding them and marking them as violation

**Comment by Majkl578** [comment]
Duplicate of _"False positives on some bundle and classes"_ - you didn't really want me to find that issue as relevant report, did you? :)

> finding them and marking them as violation

And it is exactly what is wrong, it's not a violation, it's expected. And there is no way to configure it (I don't consider `symbol-whitelist` as a sufficient solution, that's rather a hack).

**Comment by Ocramius** [comment]
> you didn't really want me to find that issue as relevant report, did you? :)

No, I simply proactively link issues together.

 > And it is exactly what is wrong, it's not a violation, it's expected.

Not in this package - the design is specifically around preventing optional dependencies upfront.

A package such as `doctrine/cache`, for example, having multiple dependencies on multiple extensions, would never pass here, but would need to be split into `doctrine/cache`, `doctrine/cache-memcache`, `doctrine/cache-redis` and so on.

Again: this is by design. Optional dependencies are a mess and should be slowly removed over time. We had massive issues in dozens of packages in `zendframework/zendframework` because of this, and it's slowly being fixed by moving forward and removing dependencies completely or splitting them into separate additions. @weierophinney can maybe add something here, but if you have "optional dependencies" (which aren't really a thing, by the way), then this package is not for you.

**Comment by Majkl578** [comment]
The description of this package clearly says:
> A CLI tool to analyze composer dependencies and verify that no unknown symbols are used in the sources of a package.

`require-dev` is also a dependency, `suggest` sort of too (suggesting a package implies that your code is aware of its (non-) existence).

> Optional dependencies are a mess and should be slowly removed over time.

Not possible until Composer has a strategy to define package _sets_/_unions_ and choosing defaults for them. Without that, you either end up with ton of useless dependencies at runtime or missing dependencies (i.e. no ORM mapping driver).

>  "optional dependencies" (which aren't really a thing)

Same as above, they are very much a thing, until package manager has a strategy to handle things better.

**Comment by Majkl578** [comment]
> because downstream consumers won't get it

Only applicable to libraries and production code.

> Suggest was proposed to be removed from composer overall

You are talking about some uncertain distant future. I am on the other hand talking about real-world situation/problem that is found in basically any larger package.

> this is a non-issue here

It's not an _issue_ here, but it's a trouble caused by rejecting the state in which PHP ecosystem currently is and will be for a while. (Even if composer adds such thing tommorow, it would take years to consider as _default_).

> **then this package is not for you**

I take this, okay. */me leaves*

Sorry that I simply wanted to make it more flexible and configurable and thus usable by more consumers.

**Comment by Ocramius** [comment]
> Only applicable to libraries and production code.

This is specifically for that: why would you need such checks otherwise?
Your `"require-dev"` is about checking that your sources and your deployable binaries do work.
Your `"require"` section is about making sure your deployable binaries (or your consumers, if you are a library) have all dependencies.
This is a `"require-dev"` package aimed at isolating issues in incorrect `"require"` scope.

 > You are talking about some uncertain distant future. I am on the other hand talking about real-world situation/problem that is found in basically any larger package.

Work towards getting to an exit code `0`. Exactly like with any legacy project with no tests or with architectural issues, this needs a lot of work and also a mental shift in how things are being handled regarding the dependency graph. We used to do the "optional dependencies" quite a lot until a few years back, and that in multiple packages: this simply increases the issues in the ecosystem, and leads to "hard to fix" scenarios where removing the optional dependency makes the package either harder to use or conflicting with other components. I suggested the correct approach to this in https://github.com/maglnet/ComposerRequireChecker/issues/70#issuecomment-393154495

 > Sorry that I simply wanted to make it more flexible and configurable and thus usable by more consumers.

It's not about widening the user-base of the package, it is about ensuring that the invariants provided by `"require"` in your package and consumers of your package make sense to consumers and to your `--no-dev` installed package.

**Comment by weierophinney** [comment]
@Majkl578 From a maintainer's point of view, "suggest" is a nightmare.

Why?

Because somebody will go and install the package, try to use that optional feature, and then file an issue saying, "feature X does not work". Maintainers will calmly point out that the feature is optional, and requires a dependency marked in the "suggest" section. The user will say they did not see it, and perhaps that dependency should be required. The maintainer will argue, "the feature is optional, that's why the dependency is optional."

This gets more heated when the user points out, "well, the dependency is in `require-dev`!" Yes, yes, it is; just because it's optional _does not mean it should not be tested_.

And then there's problems when optional features require _PHP extensions_. Don't even get me started on that.

And round and round it goes.

In ZF, we are actively attempting to split out anything that is optional functionality, particularly if such functionality requires additional dependencies, and putting them into a separate package. We have a project in place for zend-cache to split out all adapters into their own components; we will be doing so with zend-db and its adapters, too; same goes for zend-paginator (which has a couple zend-db-specific adapters). Doing this allows each to specify any code dependencies, as well as PHP extension dependencies, so that installation will fail if any of those are unmet. (With Expressive, we _already did this_ with regards to routers, template engines, and session backends, and we're doing it as well with upcoming authentication and authorization adapter packages.)

We can then "suggest" these additional packages, and _document_ the packages we know about, so that _you_, as a _consumer_, can discover what else you may need to install to get the combination of functionalities that achieve what you need.

So, while _you_ may argue packaging all optional dependencies is a "real-world situation/problem that is found in basically any larger package," what @Ocramius and I are arguing is the exact same thing: packaging anything "optional" in a larger package leads to confusion by end-users and difficulty in maintenance. It's better to split it out into more packages, each with a discrete set of _requirements_, and nothing optional.

**Comment by Ocramius** [comment]
Note: it doesn't need to be separate repositories, but the distributed package (for which `"require"` is the only important bit) shouldn't have optional deps in it

**Comment by Ocramius** [comment]
>  Look at Doctrine ORM, I don't even want to imagine the rant when YAML would be moved from `"suggest"` to `"require"`. Yet you would want to check & validate such library to detect missing dependencies.

Taking this example specifically:

```sh
composer require doctrine/orm-yaml-mapping
```

This is the correct resolution for such a scenario. If the `doctrine/orm` package uses `Yaml` somewhere, then it needs to explicitly `"require": {"symfony/yaml":"^4"}`. Whether consumers will have an additional dependency or not is less problematic than consumers having to install optional dependencies, or being burnt by an optional dependency that got inadvertently removed because another package dropped it (yes, this happens a lot too).

**Comment by Majkl578** [comment]
In such case, which driver will I get when I simply do `composer require doctrine/orm`?
None?
One that _maintainers chose as default_ (and which I might not ever use)?

**Comment by Ocramius** [comment]
> In such case, which driver will I get when I simply do `composer require doctrine/orm`?

The ones that can work with the given set of `"require"`. The PHP driver would work out of the box, the annotation one would require `doctrine/annotations` (which is [there](https://github.com/doctrine/doctrine2/blob/v2.6.1/composer.json#L21)), and for the XML driver you'd either add `"require": {"ext-xml": "*"}` or split it out like the yaml driver.

 > One that _maintainers chose as default_ (and which I might not ever use)?

This is a trade-off that comes with most libraries, and obviously needs discipline from a library author's perspective.

Another possible alternative is to not ship any drivers at all, and instead use `"require": {"doctrine/orm-driver-implementation": "^1"}`, which is then provided via `"provides": {"doctrine/orm-implementation":"1.0"}` in the implementations. This has worked really well in `doctrine/phpcr-odm`:

https://github.com/doctrine/phpcr-odm/blob/1.4.4/composer.json
